### ISSUE TITLE
Plugin adds Craft CP CSS file to site <head>

### ISSUE THREAD

**Issue by slavanossar** [poptins/craftcms-poptin-app#2]
Client requested this plugin, just tried installing it locally but having a CSS issue. It seems that enabling the plugin causes Craft's CP CSS file `craft.css` to be included in the site's `<head>`, which is overriding the site's CSS. Is this normal behaviour?

**Expected**
![image](https://user-images.githubusercontent.com/7077600/100352870-bbff2480-3041-11eb-84a1-e4f1721862a2.png)

**Actual**
![image](https://user-images.githubusercontent.com/7077600/100352815-abe74500-3041-11eb-9522-666f45a45f09.png)

**Comment by rohan0793** [comment]
Greetings, this issue was fixed in this commit -> https://github.com/poptins/craftcms-poptin-app/commit/b97e049b8a72b6d069cdbe3c3e96f70b83ad9e16

Please try updating our plugin to 1.4.0 (should be available soon in the Craft Plugin Store)

If you still have further issues using the plugin, please feel free to open a new ticket here on github or by contacting our support via live chat inside your poptin account. We are also available at contact@poptin.com.
